services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - db-data:/app
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:5000/"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  db-data: